let a = 42;
let b = "Bonjour";
let c = true;
let d = null;
let e;  
let f = [1, 2, 3];
let g = { nom: "Ali" };
let h = NaN;
console.log(String(42) + " -> " + typeof a);
console.log( String(true) + " -> " + typeof b);
console.log(String(false)+ " -> " + typeof c);
console.log(String(null)+ " -> " + typeof d);
console.log(String(undefined)+ " -> " + typeof e);
console.log(String(NaN)+ " -> " + typeof f);
console.log(String("[1, 2, 3]") + " -> " + typeof g);
console.log(String({ a: 1 })  + " -> " + typeof g);
console.log(String(NaN)+ " -> " + typeof a);